### ISSUE TITLE
Roadmap de versions pacasam

### ISSUE THREAD

**Issue by leavauchier** [IGNF/pacasam#26]
Je propose qu'on garde la configuration de débug VS COde jusqu'à une version V1.0.0 "officielle" de pacasam, qui incluerait  
- cette PR
- la PR qui cache les credentials https://github.com/IGNF/pacasam/pull/24
- hydra pour la config https://github.com/IGNF/pacasam/issues/7
- packaging (avec des commande make + twine comme ce qui se fait dans ign-pdal-tools)  https://github.com/IGNF/pacasam/issues/4

 Et a partir de là on partirait sur quelque chose d'un peu plus stable et moins mouvant, en ajoutant :
- CHANGELOG
- Semantic Versionning
-  Dockerisation https://github.com/IGNF/pacasam/issues/15
- Optimisation de la commande SQL d'interrogation de LiPaC (actuellement le filtre est fait tard et c'est donc lent)
- Choisir entre OutliersSampler et DiversitySampling (le premier semble mieux !) et intégrer ce choix dans TripleSampler.
- ...

_Originally posted by @CharlesGaydon in https://github.com/IGNF/pacasam/pull/22#discussion_r1238720257_

**Comment by CharlesGaydon** [comment]
J'ai crée une milestone pour rassembler ce qui doit être terminé avant une V1.0.0 :)
https://github.com/IGNF/pacasam/milestone/1
